---
title: Cjam.Github.Io
timezone: America/Vancouver
collections:
  posts:
    title: Posts
    output: true
  school:
    title: School
    output: false
  uploads:
    title: Uploads
    output: true
name: Colter McQuay
description: Software developer based out of Victoria BC
avatar: https://avatars3.githubusercontent.com/u/1000288?s=460&v=4
footer-links:
  dribbble: 
  email: 
  facebook: 
  flickr: 
  github: cjam
  instagram: coltermcquay
  linkedin: colter-mcquay-3574b858
  pinterest: 
  rss: 
  twitter: coltermcquay
  stackoverflow: 
  youtube: 
  googleplus: 
disqus: cjam
google_analytics: UA-126767165-1
url: https://cjam.github.io
baseurl: 
permalink: "/:title/"
version: v3.8.4
sass:
  style: expanded
plugins:
- jekyll-sitemap
- jekyll-feed
exclude:
- Gemfile
- Gemfile.lock
- LICENSE
- README.md
- CNAME
